Use artifacts to enable phpstan and cspell caching.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -58,6 +58,7 @@ workflow:
 variables:
   _CONFIG_DOCKERHUB_ROOT: "drupalci"
   # Let composer know what self.version means.
+  CACHE_TARGET: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}${CI_COMMIT_BRANCH}"
   COMPOSER_ROOT_VERSION: "${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}${CI_COMMIT_BRANCH}-dev"
   COMPOSER_ALLOW_SUPERUSER: 1
   CONCURRENCY: 24
@@ -100,7 +101,6 @@ default:
 .default-job-settings-lint: &default-job-settings-lint
   rules:
     - if: $PERFORMANCE_TEST != "1"
-
 
 ################
 # Stages
@@ -239,12 +239,44 @@ default:
 # Lint Jobs
 ################
 
+
+'Lint cache warming':
+  <<: [ *default-job-settings-lint ]
+  stage: 🪄 Lint
+  rules:
+    - if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"
+  variables:
+    KUBERNETES_CPU_REQUEST: "4"
+  script:
+    # Get the phpstan cache file from the artifacts of the latest successful
+    # job from the target branch. Allow the job to proceed and pass if the file
+    # doesn't exist.
+    - mkdir core/phpstan-tmp
+    - 'curl --location --output core/phpstan-tmp/resultCache.php "https://git.drupalcode.org/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/{$CACHE_TARGET}/raw/core/phpstan-tmp/resultCache.php?job=Lint%20cache%20warming&job_token=$CI_JOB_TOKEN" || true'
+    - 'curl --location --output core/.cspellcache "https://git.drupalcode.org/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/{$CACHE_TARGET}/raw/core/.cspellcache?job=Lint%20cache%20warming&job_token=$CI_JOB_TOKEN" || true'
+    - vendor/bin/phpstan --version
+    # Rely on PHPStan caching to execute analysis multiple times without performance drawback.
+    # Output a copy in junit.
+    - php vendor/bin/phpstan -vvv analyze --configuration=./core/phpstan.neon.dist
+    - cd core
+    - corepack enable
+    - yarn install
+    - yarn run spellcheck:core --no-must-find-files --cache --cache-strategy content
+  artifacts:
+    paths:
+      - core/phpstan-tmp/resultCache.php
+
 '🧹 PHP Static Analysis (phpstan)':
   <<: [ *default-job-settings-lint ]
   stage: 🪄 Lint
   variables:
-    KUBERNETES_CPU_REQUEST: "16"
+    KUBERNETES_CPU_REQUEST: "4"
   script:
+    # Get the phpstan cache file from the artifacts of the latest successful
+    # job from the target branch. Allow the job to proceed and pass if the file
+    # doesn't exist.
+    - mkdir core/phpstan-tmp
+    - 'curl --location --output core/phpstan-tmp/resultCache.php "https://git.drupalcode.org/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/{$CACHE_TARGET}/raw/core/phpstan-tmp/resultCache.php?job=Lint%20cache%20warming&job_token=$CI_JOB_TOKEN" || true'
     - composer validate
     - composer install --optimize-autoloader
     - if [ -n "$COMPOSER_UPDATE" ]; then
@@ -254,8 +286,8 @@ default:
     - vendor/bin/phpstan --version
     # Rely on PHPStan caching to execute analysis multiple times without performance drawback.
     # Output a copy in junit.
-    - php vendor/bin/phpstan analyze --configuration=./core/phpstan.neon.dist --error-format=gitlab > phpstan-quality-report.json || EXIT_CODE=$?
-    - php vendor/bin/phpstan analyze --configuration=./core/phpstan.neon.dist --no-progress --error-format=junit > phpstan-junit.xml || true
+    - php vendor/bin/phpstan -vvv analyze --configuration=./core/phpstan.neon.dist --error-format=gitlab > phpstan-quality-report.json || EXIT_CODE=$?
+    - php vendor/bin/phpstan -vvv analyze --configuration=./core/phpstan.neon.dist --no-progress --error-format=junit > phpstan-junit.xml || true
     - |
       if [ -n "$EXIT_CODE" ]; then
         # Output a copy in plain text for human logs.
@@ -267,11 +299,11 @@ default:
       fi
 
   artifacts:
+    # Only store the baseline if the job fails.
+    when: on_failure
     reports:
       codequality: phpstan-quality-report.json
       junit: phpstan-junit.xml
-    # Only store the baseline if the job fails.
-    when: on_failure
     paths:
       - core/.phpstan-baseline.php
 
@@ -356,16 +388,11 @@ default:
   variables:
     KUBERNETES_CPU_REQUEST: "2"
   script:
-    - if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_SHA" ]; then
-        echo "HEAD is $(git rev-parse HEAD). \$CI_MERGE_REQUEST_TARGET_BRANCH_SHA is ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA}";
-      else
-        echo "HEAD is $(git rev-parse HEAD). \$CI_MERGE_REQUEST_DIFF_BASE_SHA is ${CI_MERGE_REQUEST_DIFF_BASE_SHA}";
-      fi;
+    - 'curl --location --output core/.cspellcache "https://git.drupalcode.org/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/{$CACHE_TARGET}/raw/core/.cspellcache?job=Lint%20cache%20warming&job_token=$CI_JOB_TOKEN" || true'
     - cd core
     - corepack enable
     - yarn install
-    - git diff ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA:-$CI_MERGE_REQUEST_DIFF_BASE_SHA} --name-only 2>1 > /dev/null || (echo "Warning, cannot find changed files, converting to full clone." & (git fetch --unshallow --quiet && echo "Fetch successful."))
-    - git diff ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA:-$CI_MERGE_REQUEST_DIFF_BASE_SHA} --name-only | sed "s_^_../_" | yarn run spellcheck:core --no-must-find-files --file-list stdin
+    - yarn run spellcheck:core --no-must-find-files --cache --cache-strategy content
   cache:
     key:
       files:
@@ -378,6 +405,7 @@ default:
     expose_as: 'yarn-vendor'
     paths:
       - core/node_modules/
+      - core/.cspellcache
 
 '📔 Validatable config':
   <<: [ *default-job-settings-lint ]
